apiVersion: v1
data:
  redcount.yaml: |
    redis:
      host: {{ .Release.Name }}-redis.default.svc.cluster.local
      port: 6379
      db: 0
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-redcount
  namespace: default
