apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redcount
  labels:
    app: redcount
    release: {{ .Release.Name }}
spec:
  selector:
    app: redcount
    release: {{ .Release.Name }}
  ports:
  - protocol: "TCP"
    port: 8080
  type: ClusterIP
# exercise: modify the service type to LoadBalancer, and upgrade the release of the chart
